# Generated by Django 5.1.4 on 2025-01-09 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabrica',
            name='pais',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='f_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
